feat(data edit): Data is now editable
mi-classroom/mi-web-technologien-beiboot-ss2021-BenediktEngel pull request #16
Opened 2021-09-11 17:41 UTC by BenediktEngel

Freunde ich hab es endlich geschafft, MS6 ist eingebaut. Data ist jetzt editierbar und wird auch gespeichert. 
ADR zum neuen exif-tool folgt. 
Außerdem ja ich weis das zurücksetzen ist noch nciht möglich. Kommt aber spätestens im übernachsten PR. 
Hoffe ihr findet keine allzu wilden probleme oder Fehler ;)

2021-09-12 14:11 UTC, Narua2010 requested changes
Wenn ein Bild gespeichert wurde treten folgende Fehler auf:
1. Wenn Deutsch und Englisch gleich sind wird nur Deutsch eingespeichert, ansonsten beide.
2. Wenn bei einem Bild die Metadaten geändert wurden und bei einem zweiten Bild diese angepasst werden, werden bei mir immer die Daten des Ersten Bildes genommen.


Finde es aber gut wie du das Multilinguale gelöst hast würde mich freuen wenn du kurz mitteilst, wie du das umgesetzt hast? Dann könnte man dies ggf. auch übernehmen.

2021-09-12 14:13 UTC, Narua2010 commented
Okay interessanterweise ist der Fehler oben (2) nur beim ersten mal aufgetreten, nachm reload ging es zumindest auf der Deutschen Seite ich teste das nochmal durch.

2021-09-12 14:16 UTC, Narua2010 commented
Okay interessanterweise ist der Fehler oben (2) nur beim ersten mal aufgetreten, nachm reload ging es zumindest auf der Deutschen Seite. Konnte den Fehler auch nicht noch einmal auslösen.

Fehler 1 bleibt bestehen. Englisch muss explizit gesetzt werden.
Darüber hinaus ist der Fehler 2 auf der Englischen Seite wirklich vorhanden. Also wenn einmal in z.b. das Feld Titel im Englischen etwas explizit gespeichert wurde, wird das bei allen nachfolgenden genutzt auch wenn ich etwas anderes reinschreiben wollte.

2021-09-12 15:08 UTC, BenediktEngel commented
Okay, ja da war ich wohl gestern ein bisschen müde und hab zu lange in den Bildschirm rein geschaut :D Schau ich mir später mal an. jetzt muss erstmal das design fertig umgesetzt werden :D 
>Finde es aber gut wie du das Multilinguale gelöst hast würde mich freuen wenn du kurz mitteilst, wie du das umgesetzt hast? Dann könnte man dies ggf. auch übernehmen.
und was meinst du da? Das man manches nur in ein Feld schreiben kann oder mit dem übernehmen der texte aus dem deutschen? das müsste ich nämlich ähnlich wie du haben

2021-09-15 13:06 UTC, BenediktEngel commented
Alles klar das kommt mit dem neuen PR wo ich auch das Design gemacht habe. Hoffe das passt euch so ;)

2021-09-16 15:50 UTC, Narua2010 approved these changes
Habs im MS7 getestet - da geht nun alles :)

2021-09-19 12:36 UTC, JanKoll approved these changes

2021-09-19 15:47 UTC, merged